doc-warnings: false
test-warnings: false
strictness: medium
max-line-length: 160
#uses:
#  - django
#  - celery
#  - flask
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - docs
#ignore-patterns:
#  - ^example/doc_.*\.py$
#  - (^|/)docs(/|$)
python-targets:
  - 3